enableImmutableInstalls: true

nodeLinker: pnp

packageExtensions:
  "@crxjs/vite-plugin@*":
    dependencies:
      vite: "*"
  "@n1ru4l/graphql-live-query@*":
    dependencies:
      tslib: "*"
  "@swc/jest@*":
    dependencies:
      "@swc/core": "*"
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"
  html-webpack-plugin@*:
    dependencies:
      loader-utils: "*"
  ilp-packet@*:
    dependencies:
      long: "*"
  ilp-protocol-stream@*:
    dependencies:
      "@types/long": "*"
  inversify-express-utils@*:
    dependencies:
      "@types/express": "*"
  inversify-logger-middleware@*:
    dependencies:
      inversify: "*"
  puppeteer@*:
    dependencies:
      devtools-protocol: "*"
  react-hot-loader@*:
    dependencies:
      "@hot-loader/react-dom": "*"
  webpack@*:
    dependencies:
      "@types/json-schema": "*"

plugins:
  - ./commands/yarn/tsconfig-paths-plugin.js
  - ./commands/yarn/check-node-version.js

yarnPath: .yarn/releases/yarn-4.0.0-rc.42.cjs
