nodeLinker: pnp

packageExtensions:
  html-webpack-plugin@*:
    dependencies:
      loader-utils: "*"
  ilp-packet@*:
    dependencies:
      long: "*"
  ilp-protocol-stream@*:
    dependencies:
      "@types/long": "*"
  inversify-express-utils@*:
    dependencies:
      "@types/express": "*"
      inversify: "*"
  inversify-logger-middleware@*:
    dependencies:
      inversify: "*"
  react-hot-loader@*:
    dependencies:
      "@hot-loader/react-dom": "*"
  "@swc/jest@*":
    dependencies:
      "@swc/core": "*"
  webpack@*:
    dependencies:
      "@types/json-schema": "*"

plugins:
  - ./commands/yarn/tsconfig-paths-plugin.js
  - ./commands/yarn/check-node-version.js
  - ./commands/yarn/workspaces-lerna-list-plugin.js

yarnPath: .yarn/releases/yarn-4.0.0-rc.6.cjs
