export const SET_CURRENT_TIP_AMOUNT = 'SET_CURRENT_TIP_AMOUNT'
export const SET_PROCESS_STEP = 'SET_PROCESS_STEP'
export const SET_TIP_CREDIT_BALANCE = 'SET_TIP_CREDIT_BALANCE'

export const ADD_TIP_TO_HISTORY = 'ADD_TIP_TO_HISTORY'
export const CLEAR_TIP_TO_HISTORY = 'CLEAR_TIP_TO_HISTORY'

export const TOGGLE_EXTENSION = 'TOGGLE_EXTENSION'
export const TOGGLE_SETTINGS = 'TOGGLE_SETTINGS'

export const SET_HOTKEYS_SUBMIT = 'SET_HOTKEYS_SUBMIT'

export const UPDATE_FROM_SETTINGS = 'UPDATE_FROM_SETTINGS'
export const RESET_DEFAULTS_FROM_SETTINGS = 'RESET_DEFAULTS_FROM_SETTINGS'

export const SET_DESIGN_ITERATION = 'SET_DESIGN_ITERATION'
