#!/bin/bash
# Prevents force-pushing to master

echo -e "Pre-push Hook: Checking branch name"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
PROTECTED_BRANCHES="^(main|develop)"
# Get refs list from STDIN
REFS=$(cat)

# TODO: handle the case of empty refs
if [[ $REFS != *"$BRANCH"* && -z $SKIP_HUSKY_PRE_PUSH ]]
then
  echo "\$BRANCH = $BRANCH"
  echo "\$REFS = $REFS"
  echo -e "\n🚫 You must use (git push origin $BRANCH)\n" && exit 1
fi

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR.\n" && exit 1
fi

echo -e ">> Finished checking branch name"

exit 0
