#!/bin/bash
# Prevents pushing to protected branches

# List of branches where push is not allowed
protected_branches=("main" "develop")

# Read the standard input provided by Git
while read local_ref local_sha remote_ref remote_sha
do
    # Iterate over the protected branches
    for branch in "${protected_branches[@]}"
    do
        # Check if we're pushing to a protected branch
        if [[ "$remote_ref" == *"refs/heads/$branch"* ]]; then
            echo -e "\n🚫 Cannot push to remote $branch branch, please create your own branch and use PR.\n"
            exit 1
        fi
    done
done

echo -e ">> Push allowed\n"

exit 0
