export * from '@webmonetization/wext/tokens'
export const CoilDomain = Symbol('CoilDomain')
export const LocalStorageProxy = Symbol('LocalStorageProxy')
export const ContentRuntime = Symbol('ContentRuntime')
export const Logger = Symbol('Logger')
export const NoContextLoggerName = Symbol('Logger')
export const StreamDetails = Symbol('StreamDetails')
export const BuildConfig = Symbol('BuildConfig')
export const LoggingEnabled = Symbol('LoggingEnabled')
export const UserAgent = Symbol('UserAgent')
