name: Outer Runner
description: Runs an inner action between setup/teardown steps

inputs:
  node-version:
    description: 'version of node to run'
    required: true
  inner-steps:
    description: 'name of path to inner'
    required: true

runs:
  using: composite
  steps:
#    - name: Checkout
#      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Restore Cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.yarn
        key: v1-dependencies-${{ runner.os }}-${{ hashFiles('package.json', 'yarn.lock') }}-${{ inputs.node-version }}

    - name: Run inner steps
      uses: ${{ input.inner-steps }}

    - name: Save Cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.yarn
        key: v1-dependencies-${{ runner.os }}-${{ hashFiles('package.json', 'yarn.lock') }}-${{ inputs.node-version }}
